apiVersion: v1
kind: Service
metadata:
    name: "awvseaks-8917"
    labels:
        app: "awvseaks-8917"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "awvseaks-8917"