on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: acrworkflow1667249829207.azurecr.io
        username: ${{ secrets.acr_acrworkflow1667249829207_username }}
        password: ${{ secrets.acr_acrworkflow1667249829207_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/.devcontainer" -f  ".devcontainer/Dockerfile" -t acrworkflow1667249829207.azurecr.io/awvseaks:${{ github.sha }} --label dockerfile-path=.devcontainer/Dockerfile
        docker push acrworkflow1667249829207.azurecr.io/awvseaks:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_awvseaks_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep store-app | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace store-app`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: store-app
        container-registry-url: acrworkflow1667249829207.azurecr.io
        container-registry-username: ${{ secrets.acr_acrworkflow1667249829207_username }}
        container-registry-password: ${{ secrets.acr_acrworkflow1667249829207_password }}
        secret-name: awvseaksdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: store-app
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          acrworkflow1667249829207.azurecr.io/awvseaks:${{ github.sha }}
        imagepullsecrets: |
          awvseaksdockerauth
